[package]
name = "whois-rust"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/whois-rust"
homepage = "https://magiclen.org/whois-rust"
keywords = ["whois"]
categories = ["web-programming::websocket"]
description= "A whois client library on Rust, inspired by https://github.com/hjr265/node-whois"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/whois-rust", branch = "master" }
appveyor = { repository = "magiclen/whois-rust", branch = "master", service = "github" }

[dependencies]
serde_json = "1.0"
regex = "1.0"
lazy_static = "1.1.0"

[dependencies.validators]
version = "0.13"
features = ["serdely"]